services:

  firefox:
    image: selenium/node-firefox:4
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium
    environment:
      SE_EVENT_BUS_HOST: selenium
    networks:
      - grid
