services:

  chrome:
    image: selenium/node-chrome:4
    depends_on:
      - selenium
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - SE_EVENT_BUS_HOST=selenium
    networks:
      - grid
